package com.jgsmanaroulas.mvvmtest.mvvmtest.view.fragments;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.ViewTreeObserver;
import butterknife.Bind;
import butterknife.ButterKnife;
import com.jgsmanaroulas.mvvmtest.mvvmtest.R;
import com.jgsmanaroulas.mvvmtest.mvvmtest.model.Book;
import com.jgsmanaroulas.mvvmtest.mvvmtest.view.adapters.BookAdapter;
import com.jgsmanaroulas.mvvmtest.mvvmtest.viewmodel.BookCardVM;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by jgsmanaroulas on 08/03/16.
 */
public class BookshelfFragment extends Fragment {

    @Bind(R.id.bookshelf_recyclerview)
    RecyclerView recyclerView;

    private BookAdapter adapter;
    private ArrayList<BookCardVM> bookList;

    public BookshelfFragment(){}

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.bookshelf_fragment, container, false);
        ButterKnife.bind(this, view);

        createList();
        setUpViews();

        return view;
    }

    private void createList(){
        bookList = new ArrayList<>();
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));
        bookList.add(new BookCardVM(new Book(0,"Livro 1", "Descricao 1")));
        bookList.add(new BookCardVM(new Book(1,"Livro 2", "Descricao 2")));
        bookList.add(new BookCardVM(new Book(2,"Livro 3", "Descricao 3")));
        bookList.add(new BookCardVM(new Book(3,"Livro 4", "Descricao 4")));
        bookList.add(new BookCardVM(new Book(4,"Livro 5", "Descricao 5")));
        bookList.add(new BookCardVM(new Book(5,"Livro 6", "Descricao 6")));
        bookList.add(new BookCardVM(new Book(6,"Livro 7", "Descricao 7")));
        bookList.add(new BookCardVM(new Book(7,"Livro 8", "Descricao 8")));
        bookList.add(new BookCardVM(new Book(8,"Livro 9", "Descricao 9")));
        bookList.add(new BookCardVM(new Book(9,"Livro 10", "Descricao 10")));


    }

    private void setUpViews(){
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new GridLayoutManager(getContext(), 2));
        recyclerView.getViewTreeObserver().addOnGlobalLayoutListener(
                new ViewTreeObserver.OnGlobalLayoutListener() {
                    @Override
                    public void onGlobalLayout() {
                        recyclerView.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                        int viewWidth = recyclerView.getMeasuredWidth();
                        float cardViewWidth = getActivity().getResources().getDimension(R.dimen.bookshelf_card_width);
                        int newSpanCount = (int) Math.floor(viewWidth / cardViewWidth);
                        ((GridLayoutManager)recyclerView.getLayoutManager()).setSpanCount(newSpanCount);
                        recyclerView.getLayoutManager().requestLayout();
                    }
                });
        recyclerView.setAdapter(adapter = new BookAdapter(bookList, recyclerView));
    }
}
